name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. Set a dynamic tag variable using the current timestampp
    - name: Set dynamic image tag
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    # 2. Log into GitHub Container Registry (GHCR) using your custom PAT
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.MY_GITHUB_USERNAME }}
        password: ${{ secrets.MY_GITHUB_PAT }}

    # 3. Build the Docker image formatted for GHCR
    - name: Build the Docker image
      run: |
        docker build . \
          --file Intent-classifier-model-kubernetes/Dockerfile \
          --tag ghcr.io/${{ github.repository_owner }}/my-image-name:${{ env.TAG }}

    # 4. Push the Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my-image-name:${{ env.TAG }}

